"""Execute the quick-start notebook and render its code and outputs for MkDocs."""
from pathlib import Path
import sys

import nbformat
from nbclient import NotebookClient
from nbconvert import MarkdownExporter

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "docs/examples/quickstart.ipynb"


def main():
    notebook = nbformat.read(NOTEBOOK, as_version=4)
    nbformat.validate(notebook)
    client = NotebookClient(notebook, timeout=120, kernel_name="python3",
                            record_timing=False,
                            resources={"metadata": {"path": str(ROOT)}})
    # Use the build environment's interpreter, regardless of user kernel defaults.
    client.create_kernel_manager()
    client.km.kernel_spec.argv = [sys.executable, "-m", "ipykernel_launcher",
                                 "-f", "{connection_file}"]
    client.execute()
    nbformat.write(notebook, NOTEBOOK)
    exporter = MarkdownExporter()
    body, resources = exporter.from_notebook_node(
        notebook, resources={"output_files_dir": "assets/quickstart"})
    for filename, data in resources.get("outputs", {}).items():
        target = ROOT / "docs" / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    header = ("<!-- Generated by tools/build_example.py; edit the notebook. -->\n"
              "[Download notebook](examples/quickstart.ipynb)\n\n")
    (ROOT / "docs/example.md").write_text(header + body)
    print("Executed quickstart.ipynb and rendered docs/example.md")


if __name__ == "__main__":
    main()
