"""Render saved research notebooks for MkDocs without executing any cells."""
from pathlib import Path
import ast
import shutil

import nbformat
from nbconvert import MarkdownExporter

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
SOURCE_DIR = ROOT / "notebooks/glitch_only"
NOTEBOOKS = (
    "unequal_vs_equal_arm",
    "compare_other_codes",
    "exact_vs_hybrid",
    "raw_and_tdi_tests",
)


def main():
    destination = DOCS / "notebook-gallery"
    downloads = destination / "files"
    downloads.mkdir(parents=True, exist_ok=True)
    exporter = MarkdownExporter()
    for name in NOTEBOOKS:
        source = SOURCE_DIR / f"{name}.ipynb"
        notebook = nbformat.read(source, as_version=4)
        nbformat.validate(notebook)
        body, resources = exporter.from_notebook_node(
            notebook,
            resources={"unique_key": name,
                       "output_files_dir": f"assets/notebook-gallery/{name}"},
        )
        for filename, data in resources.get("outputs", {}).items():
            target = DOCS / filename
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
        # Images are relative to docs/, while this page is one directory deeper.
        body = body.replace("(assets/notebook-gallery/", "(../assets/notebook-gallery/")
        header = (
            "<!-- Generated by tools/render_notebooks.py; edit the source notebook. -->\n"
            f"[Download notebook](files/{name}.ipynb) · "
            f"[Source](https://github.com/jaxglitches/jaxglitches/blob/main/notebooks/glitch_only/{name}.ipynb)\n\n"
            "!!! note \"Saved notebook contents\"\n"
            "    Code, text, and outputs are displayed as saved in the repository. "
            "This documentation build does not execute or revalidate this study.\n\n"
        )
        if not resources.get("outputs"):
            header += (
                "This notebook has saved text outputs but no embedded figures. "
                "The paper PDFs referenced by its code are not included in this checkout.\n\n"
            )
        (destination / f"{name}.md").write_text(header + body)
        shutil.copyfile(source, downloads / source.name)
        print(f"Rendered saved notebook: {name}")

    source = SOURCE_DIR / "short_glitch.py"
    code = source.read_text()
    overview = ast.get_docstring(ast.parse(code))
    (destination / "short_glitch.md").write_text(
        "# Unresolved short glitches\n\n"
        "[Download script](files/short_glitch.py) · "
        "[Source](https://github.com/jaxglitches/jaxglitches/blob/main/notebooks/glitch_only/short_glitch.py)\n\n"
        "This is a research script, displayed without execution. "
        "Its local sampler outputs are not bundled in this documentation.\n\n"
        + overview + "\n\n"
        "Run from a checkout with the notebook and joint extras installed:\n\n"
        "```sh\nuv sync --extra notebook --extra joint\n"
        "cd notebooks/glitch_only\n../../.venv/bin/python short_glitch.py\n```\n\n"
        "<details markdown=\"1\">\n<summary>Full script</summary>\n\n"
        "```python\n" + code + "\n```\n\n</details>\n"
    )
    shutil.copyfile(source, downloads / source.name)
    print("Rendered script source: short_glitch")


if __name__ == "__main__":
    main()
